import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import FileUpload from "./components/FileUpload";
import { useState } from "react";
import { abi } from '../../artifacts/contracts/DocumentVerify.sol/DocumentVerify.json';
import { useReadContract, useWriteContract } from 'wagmi';
import FileRetrieve from "./components/FileRetrieve";
import VerifyDocument from "./components/VerifyDocument";



const Home: NextPage = () => {
  const[miner,setMiner]=useState("");
  const { writeContract } = useWriteContract();

  const grantminerAccess =  () => { 
    try {
       writeContract({
        abi,
        address:'0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512',
        functionName: 'GrantMinterAccess',
        args: [
            miner,
          ],
      });
    } catch (err) {
      console.error(err);
    }
  };

  
  return (
    <div>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main>
        <ConnectButton />
        <div className="max-w-sm p-6 bg-white border border-gray-200 rounded-lg shadow dark:border-gray-700">
       
        <input className="appearance-none block w-1/2 bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" placeholder="Miner Address" type="text" onChange={(e)=>{
          let temp = e.currentTarget.value;
          setMiner(temp)
        }}/>
        <button className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" onClick={grantminerAccess}>Set miner</button>
        </div>
        <div className="max-w-sm p-6 bg-white border border-gray-200 rounded-lg shadow dark:border-gray-700">
             <FileUpload></FileUpload>
        </div>
        <div className="max-w-sm p-6 bg-white border border-gray-200 rounded-lg shadow dark:border-gray-700">
          <FileRetrieve></FileRetrieve>
        </div>
        <div className="max-w-sm p-6 bg-white border border-gray-200 rounded-lg shadow dark:border-gray-700"><VerifyDocument></VerifyDocument></div>
        


        
        
      </main>
    </div>
  );
};

export default Home;
